name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Bootcamp_API/Bootcamp_API.sln
    - name: Build
      run: dotnet build src/Bootcamp_API/Bootcamp_API.sln --no-restore
    - name: Test
      run: dotnet test src/Bootcamp_API/Bootcamp_API.sln --no-build --verbosity normal